Let's create an randomly initialized 2d numpy array:            

In [3]:
import numpy as np

In [27]:
#create a 2d numpy array
a = np.random.rand(3,3)
# sets main diagonal of array equal to 1
np.fill_diagonal(a, 1)
a


array([[1.        , 0.40049048, 0.59255811],
       [0.94103978, 1.        , 0.1343366 ],
       [0.39426301, 0.53317943, 1.        ]])

In [41]:
np.tril(a)

array([[1.        , 0.        , 0.        ],
       [0.94103978, 1.        , 0.        ],
       [0.39426301, 0.53317943, 1.        ]])

In [42]:
np.triu(a)

array([[1.        , 0.40049048, 0.59255811],
       [0.        , 1.        , 0.1343366 ],
       [0.        , 0.        , 1.        ]])

In [30]:
np.diag_indices_from(a)

(array([0, 1, 2]), array([0, 1, 2]))

In [31]:
f = a.flatten()
f

array([1.        , 0.40049048, 0.59255811, 0.94103978, 1.        ,
       0.1343366 , 0.39426301, 0.53317943, 1.        ])

In [32]:
s = np.sort(f)
s

array([0.1343366 , 0.39426301, 0.40049048, 0.53317943, 0.59255811,
       0.94103978, 1.        , 1.        , 1.        ])

In [33]:
s_args = np.argsort(f)
s_args

array([5, 6, 1, 7, 2, 3, 0, 4, 8])

In [34]:
s_args[-3:]

array([0, 4, 8])

In [35]:
(rows, cols) = np.unravel_index(s_args[-3:], a.shape)
rows, cols

(array([0, 1, 2]), array([0, 1, 2]))

In [24]:
a[rows, cols]

array([4, 5, 6])

In [36]:
# gets 3 largest values in array a excluding the main diagonal:
a[np.argsort(a, axis=None)[-3:]]

IndexError: index 4 is out of bounds for axis 0 with size 3

In [39]:
np.unravel_index(np.argsort(a, axis=None)[-3:], a.shape)

(array([0, 1, 2]), array([0, 1, 2]))