In [5]:
import torch
from torch import tensor

### torch broadcasting

In [10]:
tensor([1,2,3])*tensor(2)

tensor([2, 4, 6])

In [6]:
tensor([1,2,3])*tensor([3,2,1])

tensor([3, 4, 3])

transitive, as usual multiplication     

In [7]:
tensor([3,2,1]) * tensor([1,2,3])

tensor([3, 4, 3])

In [3]:
torch.rand([3,1]) @ torch.rand([1,3])

tensor([[0.0702, 0.1086, 0.0622],
        [0.0190, 0.0295, 0.0169],
        [0.4113, 0.6367, 0.3643]])

this does not work:

In [9]:
# tensor([1,2,3])+tensor([3,2]) #runtime error

### matrix definition

row vector

In [17]:
torch.rand(3)

tensor([0.3174, 0.3434, 0.1410])

column vector

In [19]:
torch.rand(3,1) 

tensor([[0.9783],
        [0.0248],
        [0.0657]])

first index - rows, second - columns.

In [14]:
torch.rand(3,2) 

tensor([[0.3701, 0.9678],
        [0.8342, 0.5195],
        [0.5635, 0.1694]])

In [15]:
torch.rand(2,3)

tensor([[0.3237, 0.6956, 0.9680],
        [0.9431, 0.5906, 0.0959]])

In [16]:
torch.rand(2,3).T

tensor([[0.6489, 0.9638],
        [0.4266, 0.0129],
        [0.7100, 0.2072]])

### matrix multiplication

In [11]:
torch.rand([1,3]) @ torch.rand([3,1])

tensor([[0.1777]])

In [12]:
torch.rand([3,3]) @ torch.rand([3,1])

tensor([[0.8278],
        [1.5704],
        [0.6843]])

In [13]:
torch.rand([3]) @ torch.rand([3,3])

tensor([0.1798, 0.3507, 0.9338])